name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish packages
        uses: changesets/action@master
        with:
          publish: yarn release
          commit: 'chore(release): version packages'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
